title: Fazal Haroon # your name (or website title) here
logo: "/profile4.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Software Developer
  <br><br>
  <a href="kharoon187@gmail.com">kharoon187@gmail.com </a>
  <br>
  <a href="https://www.linkedin.com/in/fazalharoon/">LinkedIn Profile</a>
  <br>
  <a href="https://www.youtube.com/fazaltuts4uf">YouTube Channel</a>
  <br>
  <a href="https://github.com/Fazal-haroon/">Gihub</a> 
theme: jekyll-theme-minimal
